name: Build and test

on:
  push:
  pull_request:

defaults:
  run:
    shell: bash


env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: full

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
    - name: Install SWI Prolog on Linux
      if: ${{ matrix.os == 'ubuntu-latest' }}
      run: |
        sudo apt-add-repository ppa:swi-prolog/stable
        sudo apt-get update
        sudo apt install swi-prolog-nox
    - name: Install SWI Prolog on Windows
      if: ${{ matrix.os == 'windows-latest' }}
      run: choco install swi-prolog
    - name: Install SWI Prolog on MacOS
      if: ${{ matrix.os == 'macos-latest' }}
      run: brew install swi-prolog
    - name: Install cargo-swipl
      run: cargo install --path ./cargo-swipl
    - name: Run tests
      run: SWIPL='C:\Program Files\swipl\bin\swipl.exe' cargo swipl test
